FROM node:16

WORKDIR /build-fe

COPY sadist-fe/package.json sadist-fe/package-lock.json ./
RUN npm i
COPY sadist-fe .
RUN npm run build


FROM yakim/docker-and-compose

WORKDIR /build

COPY sadist-be .
COPY sadist-proxy ../sadist-proxy
RUN mkdir app/static
COPY --from=0 /build-fe/dist app/static
COPY deploy.sh .

CMD [ "/build/deploy.sh" ]

