version: '3'
services:

  flask:
    image: myhandicappedpet/webapp-flask
    restart: unless-stopped
    environment:
      - DATABASE_URL

  nginx:
    image: myhandicappedpet/webapp-nginx
    restart: unless-stopped
    depends_on:
      - flask
      - proxy

  proxy:
    image: myhandicappedpet/webapp-proxy
    restart: unless-stopped
    environment:
      - ENV

  chrome1:
    image: alpeware/chrome-headless-trunk
    restart: unless-stopped
    volumes:
      - chromedata:/data

  blog-app:
    image: myhandicappedpet/blog-app
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - uploads:${UPLOAD_FOLDER}

  blog-admin-app:
    image: myhandicappedpet/blog-admin-app
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - uploads:${UPLOAD_FOLDER}

  mysql:
    image: "mysql:latest"
    restart: unless-stopped
    command: "--default-authentication-plugin=mysql_native_password"
    env_file: ".env"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"

volumes:
  chromedata:
  uploads:
  mysql-data:
