version: '3'
services:

  deploy:
    image: deploy
    build:
      context: .
      dockerfile: Dockerfile-deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CA
      - CLIENT_CERT
      - CLIENT_KEY
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_MACHINE_NAME
      - DATABASE_URL
      - FLASK_SECRET_KEY
      - ENV
