version: '3'
services:

  deploy:
    image: deploy
    build:
      context: .
      dockerfile: Dockerfile-deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CERT_PATH}:/cert
    environment:
      - DOCKER_CERT_PATH=/cert
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_MACHINE_NAME
      - DATABASE_URL
      - ENV
