name: Merge branch
description: Merge one branch to another and push changes
inputs:
  repo:
    description: repository owner and name
    required: false
    default: ${GITHUB_REPOSITORY}
  from:
    description: the branch which to merge from
    required: false
    default: develop
  to:
    description: the branch which to merge to
    required: false
    default: master
  token:
    description: access token to the repo
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        mkdir tmpdir
        cd tmpdir
        git clone https://x-access-token:"${{ inputs.token }}"/github.com/${{ inputs.repo }}.git .
        git config --local user.name '${GITHUB_ACTOR}'
        git config --local user.email 'noreply@github.com' 
        git checkout ${{ inputs.to }}
        git fetch origin ${{ inputs.from }}:${{ inputs.from }}
        git merge ${{ inputs.from }} -m 'Merge ${{ inputs.from }} to ${{ inputs.to }}'
        git push origin ${{ inputs.to }}
        cd ..
        rm -rf tmpdir
