name: Run build
description: Runs docker-compose build
inputs:
  env:
    description: env to deploy (dev|staging|prod)
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        CA: ${{ secrets.CA }}
        CLIENT_CERT: ${{ secrets.CLIENT_CERT }}
        CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
        DOCKER_TLS_VERIFY: 1
        DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
        DOCKER_MACHINE_NAME: my-handicapped-pet
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        export DOCKER_CERT_PATH=$HOME/.cert
        mkdir $DOCKER_CERT_PATH
        echo -e "$CA" > $DOCKER_CERT_PATH/ca.pem
        echo -e "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
        echo -e "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
        export ENV=$INPUT_ENV
        docker-compose up --build
        docker-compose ps -q | (while read line; do code=$(docker inspect $line --format '{{.State.ExitCode}}'); if [ $code != "0" ]; then exit $code; fi; done)

