name: Run build
description: Runs docker-compose build
inputs:
  env:
    description: env to deploy (dev|staging|prod)
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export ENV=${{ inputs.env }}
        docker-compose up --build
        docker-compose ps -q | (while read line; do code=$(docker inspect $line --format '{{.State.ExitCode}}'); if [ $code != "0" ]; then exit $code; fi; done)

