# This is a workflow for building and deploying staging on push to develop

name: Check-in develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out sadist-ci under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Checks-out sadist-fe & sadist-be inside sadist-ci
    - uses: actions/checkout@v2
      with:
        repository: ilyaukin/sadist-fe
        token: ${{ secrets.ACCESS_TOKEN }}
        path: sadist-fe
    - uses: actions/checkout@v2
      with:
        repository: ilyaukin/sadist-be
        token: ${{ secrets.ACCESS_TOKEN }}
        path: sadist-be

    # Runs docker-compose build
    - uses: ./.github/actions/run-build
      with:
        env: staging