# This is a workflow for building and deploying staging on push to develop

name: Check-in develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment common for all steps
    env:
      DOCKER_TLS_VERIFY: 1
      DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
      DOCKER_MACHINE_NAME: my-handicapped-pet
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out sadist-ci under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        repository: ilyaukin/sadist-ci
        token: ${{ secrets.ACCESS_TOKEN }}
        path: .
        ref: develop

    # Checks-out sadist-fe & sadist-be inside sadist-ci
    - uses: actions/checkout@v2
      with:
        repository: ilyaukin/sadist-fe
        token: ${{ secrets.ACCESS_TOKEN }}
        path: sadist-fe
        ref: develop
    - uses: actions/checkout@v2
      with:
        repository: ilyaukin/sadist-be
        token: ${{ secrets.ACCESS_TOKEN }}
        path: sadist-be
        ref: develop

    # Sets up docker certificates
    - uses: ./.github/actions/copy-cert
      with:
        ca: ${{ secrets.CA }}
        client_cert: ${{ secrets.CLIENT_CERT }}
        client_key: ${{ secrets.CLIENT_KEY }}

    # Runs docker-compose build
    - uses: ./.github/actions/run-build
      with:
        env: staging