# This is a workflow for building and deploying prod and merge to master on manual trigger

name: Check-in master

# Controls when the action will run. Triggers the workflow manually
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment common for all steps
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out sadist-ci under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Sets up docker certificates
    - name: Dump secrets
      run: |
        echo -e "${{ secrets.AWS_SSH_KEY }}" > aws_my_handicapped_pet
        echo -e "${{ secrets.AWS_SSH_KEY_PUB }}" > aws_my_handicapped_pet.pub
        echo -e "${{ secrets.SADIST_DOT_ENV }}" > .env

    - name: Set up terraform CLI
      uses: hashicorp/setup-terraform@v3

    # Runs terraform
    - name: Terraform init, plan and apply
      run: |
        set -x
        terraform init
        terraform apply -auto-approve -var='env=prod'

    # Merges develop to master
    - name: Merge to master
      run: |
        set -x
        for repo in sadist-be sadist-blog sadist-ci sadist-fe sadist-proxy; do
          ./bin/git-clone.sh ilyaukin/$repo
          ./bin/git-merge.sh $repo develop master
        done
